spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    bbsdb:
      jdbc-url: jdbc:mysql://114.55.171.225:3306/dear?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
      username: root
      password: wst1998
      driver-class-name: com.mysql.jdbc.Driver

server:
  port: 20009
  servlet:
    context-path: /dear

redis:
  host: 114.55.171.225
  port : 6379
  pwd: Aa123456
  maxIdle: 10
  minIdle: 5
  maxTotal: 100
  maxWaitMillis: 30000
  testOnBorrow: true
  testOnReturn: false
  timeOut: 3000

swagger:
  show: true

pagehelper:
  auto-dialect: true
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: true


logging:
  level:
    com.dear.mapper: DEBUG

fileSetting:
  savePath: C:/dearTemp
  accessPath: file


wx:
  #小程序appid
  appid: wxd7570919d63f15d6
  #小程序appSecret
  secret: adc468bed5ba1924f419fa23a4195d17
